#:schema node_modules/wrangler/config-schema.json
name = "laburen-challenge-mcp"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Cloudflare D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "laburen-challenge-db"
database_id = "91a940ad-ee7e-4fa8-b853-950e5e5880ae"

# Variables de entorno (opcional)
# [vars]
# ENVIRONMENT = "production"
